export const SUBJECTS = [
  {
    id: "grammar",
    name: "Grammar",
    icon: "📝",
    color: "from-purple-500 to-indigo-600",
    chapters: [
      "Tenses",
      "Articles (A, An, The)",
      "Prepositions",
      "Subject-Verb Agreement",
      "Voice (Active/Passive)",
      "Narration (Direct/Indirect)",
      "Error Spotting",
      "Fill in the Blanks",
      "Sentence Improvement",
      "Synonyms & Antonyms",
      "Idioms & Phrases",
      "Miscellaneous",
    ],
  },
  {
    id: "gk",
    name: "General Knowledge",
    icon: "🌍",
    color: "from-blue-500 to-cyan-600",
    chapters: [
      "Indian History",
      "Indian Geography",
      "Indian Polity",
      "Indian Economy",
      "Science & Technology",
      "Sports",
      "Awards & Honours",
      "Important Days",
      "Static GK",
      "Miscellaneous",
    ],
  },
  {
    id: "history",
    name: "History",
    icon: "🏛️",
    color: "from-amber-500 to-orange-600",
    chapters: [
      "Ancient India",
      "Medieval India",
      "Modern India",
      "World History",
      "Indian Freedom Struggle",
      "Post Independence India",
      "Art & Culture",
      "Miscellaneous",
    ],
  },
  {
    id: "reasoning",
    name: "Reasoning",
    icon: "🧩",
    color: "from-pink-500 to-rose-600",
    chapters: [
      "Coding-Decoding",
      "Blood Relations",
      "Direction Sense",
      "Seating Arrangement",
      "Syllogism",
      "Inequalities",
      "Puzzle Test",
      "Input-Output",
      "Alphanumeric Series",
      "Miscellaneous",
    ],
  },
  {
    id: "mathematics",
    name: "Mathematics",
    icon: "🔢",
    color: "from-emerald-500 to-teal-600",
    chapters: [
      "Number System",
      "Simplification",
      "Percentage",
      "Profit & Loss",
      "Ratio & Proportion",
      "Time & Work",
      "Time & Distance",
      "Average",
      "Simple & Compound Interest",
      "Miscellaneous",
    ],
  },
  {
    id: "quiz",
    name: "Quiz",
    icon: "🎯",
    color: "from-violet-500 to-purple-600",
    chapters: [
      "Mixed Quiz",
      "Current Affairs",
      "Science Quiz",
      "Sports Quiz",
      "Geography Quiz",
      "Literature Quiz",
      "Entertainment Quiz",
      "Miscellaneous",
    ],
  },
] as const;

export const TEST_CONFIGS = [
  { id: "short", questions: 15, time: 20, label: "Quick Test" },
  { id: "long", questions: 20, time: 25, label: "Full Test" },
] as const;

export type SubjectId = (typeof SUBJECTS)[number]["id"];
export type Chapter = string;